server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://localhost:27017/orders

kafka:
  bootstrap-servers: "127.0.0.1:9092"

spring.kafka:
  producer:
    keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
    valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
    properties:
      schema:
        registry:
          url: "http://127.0.0.1:8081"
  consumer:
    group-id: "OrderCreation-event"
    keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
    autoOffsetReset: "earliest"
    properties:
      schema:
        registry:
          url: "http://127.0.0.1:8081"
      specific:
        avro:
          reader: "true"
