version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: orderCycleDB
    restart: unless-stopped

volumes:
  mongo_data:
